name: Sync Markdown to R2

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Markdown files to R2
        uses: zhaijunxiao/r2-dir-sync@v1.0.1 # Or another suitable R2 sync action
        with:
          accountid: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET_NAME }}
          source: ${{ github.workspace }}/src/prose # e.g., "docs" or "content"
          destination: "prose" # Optional: specify a subdirectory in R2
          filenamePattern: .*